const data = [
    {
      name: 'Graphene 360+ Gravity Pro',
      type: 'head',
      popularity: 1,
      price: 220,
      isInStock: true,
    },
    {
      name: 'Pure Drive',
      type: 'babolat',
      popularity: 2,
      price: 210,
      isInStock: false,
    },
    {
      name: 'EZONE Tour',
      type: 'yonex',
      popularity: 3,
      price: 230,
      isInStock: true,
    },
    {
      name: 'Graphene 360+ Radical Pro',
      type: 'head',
      popularity: 4,
      price: 220,
      isInStock: false,
    },
    {
      name: 'Srixon CX 200 Tour',
      type: 'dunlop',
      popularity: 5,
      price: 250,
      isInStock: true,
    },
    {
      name: 'Pure Drive Tour',
      type: 'babolat',
      popularity: 6,
      price: 210,
      isInStock: false,
    },
    {
      name: 'Graphene 360+ Speed Pro Novak Edition',
      type: 'head',
      popularity: 7,
      price: 170,
      isInStock: true,
    },
    {
      name: 'V Core 98 305g',
      type: 'yonex',
      popularity: 8,
      price: 230,
      isInStock: true,
    },
    {
      name: 'Evo Drive',
      type: 'babolat',
      popularity: 9,
      price: 190,
      isInStock: false,
    },
    {
        name: 'Graphene 360+ Radical Lite',
        type: 'head',
        popularity: 10,
        price: 160,
        isInStock: false,
      },
  ]